### ISSUE TITLE
YAML code block highlighting not working

### ISSUE THREAD

**Issue by aioue** [jonathanyeung/mark-sharp#26]
### Describe the bug.

YAML highlighting should be at least similar to the code editor pane.

<img width="936" alt="image" src="https://github.com/user-attachments/assets/11ed45b8-2761-4451-94c3-8091730cfa3f">

### Repro Steps

This text, then toggle Mark Sharp Spit View via command pallet.

## Access

1. Install the VSCode Remote Development extension.

    ```yaml
    Name: Remote Development
    Id: ms-vscode-remote.vscode-remote-extensionpack
    Description: An extension pack that lets you open any folder in a container, on a remote machine, or in WSL and take advantage of VS Code's full feature set.
    Publisher: Microsoft
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack
    ```

### Version

1.5.0

### What platform are you seeing the problem on?

Mac OS
