### ISSUE TITLE
How to properly escape dollar sign $

### ISSUE THREAD

**Issue by gretthunberg** [jonathanyeung/mark-sharp#66]
### Describe the bug.

I am unable to use the dollar sign. If two dollar signs are in a single line, the text between them turns into a LaTeX formula. If I try escaping them with backslash, the text between them turns red.

### Repro Steps

For example, in the following line:

Both set were available US\\$60 for 10 MHz version and US\\$90 for 12 MHz version in quantities of 100.

"60 for 10 MHz version and US\\" turns red

### Version

1.6.2

### What platform are you seeing the problem on?

Linux

**Comment by gretthunberg** [comment]
Also, hyphens incorrectly rendered as bullets in indented code blocks within list items

### Description
Code blocks containing hyphens (`-`) are incorrectly rendered as bullet points when the code block is indented within a list item.

### Reproduction Steps
This renders incorrectly (hyphens become bullets):
```markdown
- **Strapi + Markdown Plugin**
  - Markdown field type
  - REST/GraphQL API
  - Docker-compose example:
    ```yaml
    services:
      postgres:
        image: postgres:15
      strapi:
        image: strapi/strapi:4.11.7
        depends_on:
          - postgres      # This hyphen becomes a bullet
    ```
```

This renders correctly (no indentation):

```yaml
services:
  postgres:
    image: postgres:15
  strapi:
    image: strapi/strapi:4.11.7
    depends_on:
      - postgres              # This hyphen renders correctly
```

### Expected Behavior
Hyphens in code blocks should render as literal hyphens, regardless of indentation level.

### Current Behavior
The markdown parser appears to be processing indented code blocks as if they were part of the list syntax, causing hyphens to be interpreted as list markers.

### Environment
- Markdown viewer: 1.6.2
- Platform: Linux
